### ISSUE TITLE
Migrate from React.PropTypes

### ISSUE THREAD

**Issue by monstersintokyo** [erikras/react-native-listener#11]
With react [V.15.5](https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html) PropTypes moved to a seperate [package](https://www.npmjs.com/package/prop-types).

Hence a warning is thrown:
_Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead._

See [Migrating from React.PropTypes](https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html#migrating-from-react.proptypes).

**Comment by erikras** [comment]
Fixed by #12.

**Comment by erikras** [comment]
Published fix in [`v1.0.2`](https://github.com/erikras/react-native-listener/releases/tag/v1.0.2).
