### ISSUE TITLE
Update to react 0.14

### ISSUE THREAD

**Issue by xnomadbb** [erikras/react-native-listener#3]
Looks like all that's needed is to use ReactDOM.findDOMNode (from react-dom) rather than getDOMNode. It runs fine as-is but warns about that.

**Comment by erikras** [comment]
I'll get right on that.

I didn't know that anyone was using this project. May I ask what you are using it for?

**Comment by erikras** [comment]
Fixed in `v1.0.0`.

**Comment by xnomadbb** [comment]
Thank you!

https://github.com/xnomadbb/arrtorrent/blob/master/client/js/components/context-menu-manager.jsx#L106-L113

I'm using it to handle a context menu. I need to detect clicks outside of the menu area in order to close it. React makes it painful to add a full-page overlay high in the DOM tree when the context menu is created in a deeply nested component, and I don't want to listen for clicks on the entire document. Instead I make a full-page overlay that closes the menu on click, then put the menu inside _that_. NativeListener is used to prevent menu clicks from bubbling up to the overlay and closing the context menu. Probably a cleaner way to go about this, that's the first thing I tried that works.

**Comment by erikras** [comment]
Very cool. I originally wrote it to allow me to overlay a react component over a non-react html5 video, and the video was hearing all my click events.
