### ISSUE TITLE
What other event listener properties are supported?

### ISSUE THREAD

**Issue by mcmunder** [erikras/react-native-listener#5]
First: thanks for the nice component! It works great when listening for `onClick` and `onKeyDown` events. However, I am having problems getting it to work with other event listeners like eg. `onChange`. For example:

``` js

//...

handleChange (event) {
    console.log(event)
  }

  render () {
    return (
      <div>
        <NativeListener onChange={this.handleChange.bind(this)}>
          <input type="text" />
        </NativeListener>
      </div>
    )
  }

//...
```

Does not log anything to the console. Am I getting something totally wrong here or are other event listeners not supported? Thanks for any advice!

**Comment by bundance** [comment]
A quick check of the code shows these are the events that are supported:

-   'KeyDown',
-   'KeyPress',
-   'KeyUp',
-   'Click',
-   'ContextMenu',
-   'DoubleClick',
-   'Drag',
-   'DragEnd',
-   'DragEnter',
-   'DragExit',
-   'DragLeave',
-   'DragOver',
-   'DragStart',
-   'Drop',
-   'MouseDown',
-   'MouseEnter',
-   'MouseLeave',
-   'MouseMove',
-   'MouseOut',
-   'MouseOver',
-   'MouseUp'
