### ISSUE TITLE
Wrapped NativeListener fails

### ISSUE THREAD

**Issue by Aryk** [erikras/react-native-listener#8]
If you have components that wrap NativeListener, the outer element will not catch events after what I think is the first rerendering. I fixed it by inserting a div between the elements. Not a huge deal, just was kinda of hard to track down. It might be related to how it creates the component in the HOC.

**Comment by erikras** [comment]
Can you give some example code to illustrate what you mean?

**Comment by Aryk** [comment]
I'm trying to remember the exact issue. It was something like:

```ts
<Custom>
  <NativeListener>
    
  </NativeListener>
</Custom>
```

and I needed to do this:


```ts
<Custom>
  <div>
    <NativeListener>
    </NativeListener>
  </div>
</Custom>
```

So in the first example Custom will not catch events that bubble up (like onClick) from within the NativeListener. This behavior starts happening after the first update to the components. I think that's what the issue was. It's hard to remember. It's been a few months.

**Comment by erikras** [comment]
Thanks for trying. It doesn't make much sense, given my understanding of event bubbling and React. `NativeListener` isn't creating any new elements, it's just outputting `this.props.children` in its `render()` method.

**Comment by Aryk** [comment]
Got it, let me get back to you when I encounter it again! and give more detail.
